import { useEffect, useMemo, useState } from "react";
import { Layout } from "@/components/Layout";
import { formatCurrency, formatNumberCO, parseNumberCO } from "@/lib/utils";
import { Search, Trash2 } from "lucide-react";

const API = `${import.meta.env.BASE_URL}api`.replace(/\/+/g, "/").replace(/\/$/, "");
const MOTIVOS = ["Producto dañado", "Arreglo para trabajador", "Pérdida", "Consumo interno", "Producto vencido", "Otro"];
type Producto = { id: number; nombre: string; codigo: string; stockLocal: number; stockBodega: number; precioCompra: number; precioVentaSinIva: number };
type Registro = { id: number; operacionId: string; motivo: string; motivoOtro?: string | null; observacion?: string | null; productoNombre: string; cantidad: number; precioCompra: number; precioVenta: number; creadoEn: string };

function necesitaConfirmacion(texto: string) { const limpio = texto.replace(/[\s'$]/g, ""); const partes = limpio.split("."); return !limpio.includes(",") && partes.length === 2 && partes[1].length === 3; }

export default function DescuentosInventario() {
  const [productos, setProductos] = useState<Producto[]>([]); const [registros, setRegistros] = useState<Registro[]>([]); const [busqueda, setBusqueda] = useState("");
  const [cantidades, setCantidades] = useState<Record<number, string>>({}); const [confirmados, setConfirmados] = useState<Record<number, boolean>>({}); const [motivo, setMotivo] = useState(MOTIVOS[0]); const [motivoOtro, setMotivoOtro] = useState(""); const [observacion, setObservacion] = useState(""); const [mensaje, setMensaje] = useState(""); const [guardando, setGuardando] = useState(false);
  const cargar = async () => { const [p, h] = await Promise.all([fetch(`${API}/inventario`).then((r) => r.json()), fetch(`${API}/descuentos-inventario`).then((r) => r.json())]); setProductos(p); setRegistros(h); };
  useEffect(() => { void cargar(); }, []);
  const visibles = useMemo(() => productos.filter((p) => `${p.nombre} ${p.codigo}`.toLowerCase().includes(busqueda.toLowerCase())), [productos, busqueda]);
  const grupos = useMemo(() => [...registros.reduce((m, r) => m.set(r.operacionId, [...(m.get(r.operacionId) || []), r]), new Map<string, Registro[]>()).values()], [registros]);
  const guardar = async () => {
    setMensaje(""); const items = Object.entries(cantidades).filter(([, cantidad]) => cantidad.trim());
    if (!items.length) { setMensaje("Selecciona cantidades para uno o varios productos."); return; }
    if (motivo === "Otro" && !motivoOtro.trim()) { setMensaje("Especifica el motivo."); return; }
    if (items.some(([id, cantidad]) => necesitaConfirmacion(cantidad) && !confirmados[Number(id)])) { setMensaje("Confirma la interpretación de las cantidades marcadas."); return; }
    setGuardando(true); try { const res = await fetch(`${API}/descuentos-inventario`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ motivo, motivoOtro, observacion, items: items.map(([productoId, cantidad]) => ({ productoId: Number(productoId), cantidad: parseNumberCO(cantidad) })) }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setCantidades({}); setConfirmados({}); setObservacion(""); setMensaje("Descuento registrado."); await cargar(); } catch (e) { setMensaje(e instanceof Error ? e.message : "No se pudo guardar"); } finally { setGuardando(false); }
  };
  return <Layout><div className="space-y-6"><div><h1 className="text-2xl font-display font-bold">Descuentos de inventario</h1><p className="text-sm text-muted-foreground mt-1">Se descuenta primero de Local y luego de Bodega.</p></div>
    <section className="bg-card border border-border rounded-xl p-5 space-y-4"><div className="grid sm:grid-cols-2 gap-3"><label className="text-sm">Motivo<select value={motivo} onChange={(e) => setMotivo(e.target.value)} className="mt-1 w-full bg-background border border-border rounded-lg px-3 py-2">{MOTIVOS.map((m) => <option key={m}>{m}</option>)}</select></label>{motivo === "Otro" && <label className="text-sm">Especifica el motivo<input value={motivoOtro} onChange={(e) => setMotivoOtro(e.target.value)} className="mt-1 w-full bg-background border border-border rounded-lg px-3 py-2" /></label>}</div><label className="text-sm">Observación<textarea value={observacion} onChange={(e) => setObservacion(e.target.value)} rows={2} className="mt-1 w-full bg-background border border-border rounded-lg px-3 py-2" /></label><div className="relative"><Search className="absolute left-3 top-2.5 w-4 h-4" /><input value={busqueda} onChange={(e) => setBusqueda(e.target.value)} placeholder="Buscar producto" className="w-full pl-9 bg-background border border-border rounded-lg px-3 py-2" /></div><div className="max-h-64 overflow-auto divide-y divide-border">{visibles.map((p) => <div key={p.id} className="flex items-center justify-between gap-3 py-2"><div><p className="text-sm font-medium">{p.nombre}</p><p className="text-xs text-muted-foreground">{p.codigo} · Local {p.stockLocal} · Bodega {p.stockBodega}</p></div><input value={cantidades[p.id] || ""} onChange={(e) => setCantidades((x) => ({ ...x, [p.id]: e.target.value }))} placeholder="0,25" inputMode="decimal" className="w-24 text-right bg-background border border-border rounded-lg px-2 py-1.5" /></div>)}</div>
      {Object.entries(cantidades).filter(([, c]) => c.trim()).map(([id, texto]) => <div key={id} className="text-xs border border-border rounded-lg p-3 flex justify-between gap-3"><div><p>Escribiste <strong>{texto}</strong>; se interpretará como <strong>{formatNumberCO(parseNumberCO(texto))}</strong>.</p><p className="text-muted-foreground">El sistema descontará primero de Local y completará desde Bodega.</p>{necesitaConfirmacion(texto) && <label className="flex gap-2 mt-2"><input type="checkbox" checked={Boolean(confirmados[Number(id)])} onChange={(e) => setConfirmados((x) => ({ ...x, [Number(id)]: e.target.checked }))} /> Confirmo esta interpretación</label>}</div><button title="Quitar" onClick={() => setCantidades((x) => { const n = { ...x }; delete n[Number(id)]; return n; })}><Trash2 className="w-4 h-4 text-destructive" /></button></div>)}{mensaje && <p className="text-sm text-primary">{mensaje}</p>}<button onClick={() => void guardar()} disabled={guardando} className="px-4 py-2 rounded-lg bg-primary text-primary-foreground disabled:opacity-50">{guardando ? "Guardando..." : "Registrar descuento"}</button></section>
    <section className="space-y-4"><h2 className="text-xl font-bold">Historial</h2>{grupos.map((grupo) => <div key={grupo[0].operacionId} className="bg-card border border-border rounded-xl overflow-hidden"><div className="p-3 border-b border-border text-sm"><strong>{grupo[0].motivo === "Otro" ? grupo[0].motivoOtro : grupo[0].motivo}</strong> · {new Date(grupo[0].creadoEn).toLocaleString("es-CO")}</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-muted text-left"><th className="p-3">Producto</th><th className="p-3">Cantidad</th><th className="p-3">P. compra</th><th className="p-3">P. venta</th><th className="p-3">Total compra</th><th className="p-3">Total venta</th></tr></thead><tbody>{grupo.map((r) => <tr key={r.id} className="border-t border-border"><td className="p-3">{r.productoNombre}</td><td className="p-3">{formatNumberCO(r.cantidad)}</td><td className="p-3">{formatCurrency(r.precioCompra)}</td><td className="p-3">{formatCurrency(r.precioVenta)}</td><td className="p-3">{formatCurrency(r.cantidad * r.precioCompra)}</td><td className="p-3">{formatCurrency(r.cantidad * r.precioVenta)}</td></tr>)}</tbody><tfoot><tr className="border-t-2 border-border font-bold"><td className="p-3">Totales</td><td className="p-3">{formatNumberCO(grupo.reduce((s, r) => s + r.cantidad, 0))}</td><td /><td /><td className="p-3">{formatCurrency(grupo.reduce((s, r) => s + r.cantidad * r.precioCompra, 0))}</td><td className="p-3">{formatCurrency(grupo.reduce((s, r) => s + r.cantidad * r.precioVenta, 0))}</td></tr></tfoot></table></div></div>)}</section></div></Layout>;
}