export * from "./inventario";
export * from "./ventas";
export * from "./creditos";
export * from "./compras";
export * from "./manoobra";
export * from "./trabajadores";
export * from "./notas";
export * from "./historial";
export * from "./historial_precios";
